create database LEARNMATCH;
use  LEARNMATCH;

CREATE TABLE MATERIA (
    PK_MATERIA INT(6) PRIMARY KEY,
    NOMBRE_MATERIA VARCHAR(45) NOT NULL,
    AREA VARCHAR(45) NOT NULL,
    DESCRIPCION VARCHAR(45) NOT NULL
);

CREATE TABLE USUARIOELIMINADO (
    PK_USUARIO_ELIMINADO INT(10) PRIMARY KEY,
    CORREO_ELECTRONICO_E VARCHAR(45) NOT NULL,
    ESTATUS_REPORTADO VARCHAR(45) NOT NULL
);


CREATE TABLE COMUNICACIOZG (
PK_REUNION INT(10) PRIMARY KEY,
ESTADOREUNION INT(1) NOT NULL,
FK_EMPAREJAMIENTO INT(10) NOT NULL,
FK_USUARIO1 INT(10) NOT NULL,
FK_USUARIO2 INT(10) NOT NULL
);


CREATE TABLE EMPAREJAMIENTO (
PK_EMPAREJAMIENTO INT (10) PRIMARY KEY,
ESTADOEMPAREJAMIENTO INT (10) NOT NULL,
FK_USUARIO1 INT(10) NOT NULL,
FK_USUARIO2 INT(10) NOT NULL
);


CREATE TABLE INFORMACIONUSUARIO (
PK_USUARIO INT(6) PRIMARY KEY,
ESTATUSUSUARIO INT(1) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO_PATERNO VARCHAR(30) NOT NULL,
APELLIDO_MATERNO VARCHAR(30) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
REPORTADO INT(1),
CALIFICACION DECIMAL(10, 2),
FK_DEFICIENCIA1 INT(6) NOT NULL,
FK_DEFICIENCIA2 INT(6) NOT NULL,
FK_DEFICIENCIA3 INT(6) NOT NULL,
FK_ENSEÑANZA1 INT(6) NOT NULL,
FK_ENSEÑANZA2 INT(6) NOT NULL,
FK_ENSEÑANZA3 INT(6) NOT NULL,
FECHA_CREACION DATE,
FECHA_BORRADO DATE
);

CREATE TABLE USUARIOCUENTA (
PK_CUENTA INT(6) PRIMARY KEY,
FK_INFOUSUARIO INT(6) NOT NULL,
ROL_USUARIO INT (1) NOT NULL,
PSW VARCHAR(1) NOT NULL
);


